### ISSUE TITLE
gdbm.h has been moved in libgdbm-compat-dev in debian testing

### ISSUE THREAD

**Issue by sapristi** [ocaml/dbm#4]
Using debian testing, the package needed for compiling dbm is now libgdbm-compat-dev.

**Comment by xavierleroy** [comment]
Thanks for the report.  I updated the README.md instructions.  Will have a look at the OPAM package.

**Comment by jpdeplaix** [comment]
AFAIK the opam package cannot be fixed since opam1 doesn't handle installing different package depending on the distribution version (e.g. ```libgdbm-dev``` with debian stable vs. ```libgdbm-compat-dev``` with >= debian testing)
However this can be fixed using opam2 but the release is still month away.
One thing that can be done however is to port dbm to use either versions but I don't know if it's possible. I'll give it a shot today.
